import { useState } from 'react'
import './App.css'

type Segment = { name: string; count: string; share: number; color: string; description: string; value: string }
const segments: Segment[] = [
  { name: 'Power buyers', count: '2,841', share: 31, color: 'coral', description: 'High frequency, high basket size', value: '$1.8M' },
  { name: 'Growing loyalists', count: '1,964', share: 22, color: 'blue', description: 'Momentum building across channels', value: '$924K' },
  { name: 'Deal seekers', count: '1,427', share: 16, color: 'yellow', description: 'Responsive to timely incentives', value: '$486K' },
  { name: 'At-risk', count: '1,103', share: 12, color: 'ink', description: 'Previously active, now quiet', value: '$392K' },
]

function App() {
  const [activeSegment, setActiveSegment] = useState('Power buyers')
  const [spend, setSpend] = useState(780)
  const [visits, setVisits] = useState(8)
  const [orders, setOrders] = useState(4)
  const [notice, setNotice] = useState('')
  const score = Math.min(99, Math.round(42 + spend / 28 + visits * 1.8 + orders * 2.4))
  const predicted = score > 82 ? 'Power buyer' : score > 67 ? 'Growing loyalist' : score > 52 ? 'Deal seeker' : 'At-risk'
  function exportReport() { setNotice('Report ready to download'); window.setTimeout(() => setNotice(''), 2600) }

  return <div className="shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">⌁</span><span>mosaic<span className="brand-dot">.</span></span></div><div className="workspace-label">WORKSPACE</div><button className="workspace-switch"><span className="workspace-avatar">AC</span><span>Acme Commerce</span><span className="chevron">⌄</span></button><nav><div className="nav-label">ANALYTICS</div><button className="nav-item active"><span>◈</span> Overview</button><button className="nav-item"><span>◌</span> Segments <span className="nav-count">4</span></button><button className="nav-item"><span>⌁</span> Journeys</button><button className="nav-item"><span>◒</span> Experiments</button><div className="nav-label lower">MANAGE</div><button className="nav-item"><span>⊙</span> Audiences</button><button className="nav-item"><span>⚙</span> Settings</button></nav><div className="sidebar-footer"><div className="avatar">JD</div><div><strong>Jordan Davis</strong><small>Growth team</small></div><span className="more">•••</span></div></aside>
    <main className="main"><header className="topbar"><div className="breadcrumb">Analytics <span>/</span> Overview</div><div className="header-actions"><span className="status"><i></i> Model synced 8m ago</span><button className="icon-button" aria-label="Notifications">♧<b></b></button><button className="export" onClick={exportReport}>↥ <span>Export report</span></button></div></header>
      <div className="content"><section className="intro"><div><p className="eyebrow">MONDAY, SEP 12, 2026</p><h1>Good morning, Jordan <span>✦</span></h1><p className="subhead">Your customer intelligence, at a glance.</p></div><div className="range"><button>Last 30 days <span>⌄</span></button></div></section>
        <section className="metrics"><div className="metric"><div className="metric-top"><span>Total customers</span><span className="metric-icon cyan">♧</span></div><strong>9,214</strong><p><em className="up">↗ 8.4%</em> vs previous period</p></div><div className="metric"><div className="metric-top"><span>Avg. customer value</span><span className="metric-icon green">$</span></div><strong>$684</strong><p><em className="up">↗ 12.1%</em> vs previous period</p></div><div className="metric"><div className="metric-top"><span>Active segments</span><span className="metric-icon coral">◌</span></div><strong>4</strong><p><em className="neutral">● Stable</em> this period</p></div><div className="metric"><div className="metric-top"><span>Model confidence</span><span className="metric-icon purple">✧</span></div><strong>94.8%</strong><p><em className="up">↗ 2.6%</em> vs previous period</p></div></section>
        <section className="grid-top"><div className="panel distribution"><div className="panel-heading"><div><p className="section-kicker">CUSTOMER MIX</p><h2>Segment distribution</h2></div><button className="dots">•••</button></div><div className="donut-row"><div className="donut"><div className="donut-center"><strong>9,214</strong><small>customers</small></div></div><div className="legend">{segments.map((segment) => <button className={`legend-item ${activeSegment === segment.name ? 'selected' : ''}`} key={segment.name} onClick={() => setActiveSegment(segment.name)}><span className={`dot ${segment.color}`}></span><span>{segment.name}</span><strong>{segment.share}%</strong></button>)}</div></div><div className="distribution-foot"><span>▣ Model: <b>RFM + behavioral</b></span><span>Updated today</span></div></div><div className="panel insight"><div className="insight-label"><span className="spark">✦</span> AI INSIGHT</div><h2>Power buyers are your growth engine</h2><p>This segment drives <strong>42% of total revenue</strong> with only 31% of your customer base. Their repeat purchase window is narrowing.</p><div className="insight-action"><span><b>Suggested play</b><small>Launch a VIP early-access campaign</small></span><button aria-label="Open insight">↗</button></div></div></section>
        <section className="segments-section"><div className="section-heading"><div><p className="section-kicker">YOUR AUDIENCE</p><h2>Customer segments <span className="small-count">4 active</span></h2></div><button className="view-all">View all segments <span>→</span></button></div><div className="segment-grid">{segments.map((segment) => <button className={`segment-card ${activeSegment === segment.name ? 'active' : ''}`} key={segment.name} onClick={() => setActiveSegment(segment.name)}><div className="segment-card-top"><span className={`segment-dot ${segment.color}`}></span><span className="segment-arrow">↗</span></div><h3>{segment.name}</h3><p>{segment.description}</p><div className="segment-value"><strong>{segment.count}</strong><span>customers</span></div><div className="segment-bottom"><span className="mini-bar"><i className={segment.color} style={{ width: `${segment.share * 2.7}%` }}></i></span><span>{segment.value} value</span></div></button>)}</div></section>
        <section className="panel what-if"><div className="what-copy"><p className="section-kicker">AI PLAYGROUND</p><h2>What-if profile</h2><p>Adjust the signals to see how the model classifies a customer.</p><div className="prediction"><span className="prediction-icon">✦</span><span>Predicted segment</span><strong>{predicted}</strong><b>{score}% confidence</b></div></div><div className="sliders"><label>Monthly spend <output>${spend}</output><input type="range" min="100" max="2000" value={spend} onChange={(event) => setSpend(Number(event.target.value))} /></label><label>Monthly visits <output>{visits}</output><input type="range" min="1" max="20" value={visits} onChange={(event) => setVisits(Number(event.target.value))} /></label><label>Orders this quarter <output>{orders}</output><input type="range" min="0" max="12" value={orders} onChange={(event) => setOrders(Number(event.target.value))} /></label></div></section>
      </div>{notice && <div className="toast">✓ {notice}</div>}</main></div>
}
export default App
